name: Build and Release

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pywebview pyinstaller

    - name: Build project
      run: |
        pyinstaller --onefile --windowed --add-data="dist:dist" --icon="dist/favicon.ico" --name="CialloTools" main.py
        
      working-directory: ${{ github.workspace }}

    

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: dist
