name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pywebview pyinstaller  

    - name: Build project
      run: |
        pyinstaller --onefile --windowed --add-data="dist:dist" --icon="dist/favicon.ico" main.py

    - name: Verify build output
      run: |
        if [ ! -f "dist/cialloTools.exe" ]; then
          echo "Build output not found!"
          exit 1
        fi

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: dist/cialloTools.exe
